package com.fmall.springmvc.generate.mapper;

import com.fmall.springmvc.generate.pojo.MyUser;
import com.fmall.springmvc.generate.pojo.MyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    int countByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    int deleteByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    int insert(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    int insertSelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    List<MyUser> selectByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    int updateByExampleSelective(@Param("record") MyUser record, @Param("example") MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    int updateByExample(@Param("record") MyUser record, @Param("example") MyUserExample example);
}