package com.fmall.springmvc.generate.mapper;

import com.fmall.springmvc.generate.pojo.SavingsBank;
import com.fmall.springmvc.generate.pojo.SavingsBankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SavingsBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int countByExample(SavingsBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int deleteByExample(SavingsBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int deleteByPrimaryKey(Integer bankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int insert(SavingsBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int insertSelective(SavingsBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    List<SavingsBank> selectByExample(SavingsBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    SavingsBank selectByPrimaryKey(Integer bankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int updateByExampleSelective(@Param("record") SavingsBank record, @Param("example") SavingsBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int updateByExample(@Param("record") SavingsBank record, @Param("example") SavingsBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int updateByPrimaryKeySelective(SavingsBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_bank
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    int updateByPrimaryKey(SavingsBank record);
}