package com.fmall.springmvc.generate.mapper;

import com.fmall.springmvc.generate.pojo.SavingsRegion;
import com.fmall.springmvc.generate.pojo.SavingsRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SavingsRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int countByExample(SavingsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int deleteByExample(SavingsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int deleteByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int insert(SavingsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int insertSelective(SavingsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    List<SavingsRegion> selectByExample(SavingsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    SavingsRegion selectByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int updateByExampleSelective(@Param("record") SavingsRegion record, @Param("example") SavingsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int updateByExample(@Param("record") SavingsRegion record, @Param("example") SavingsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int updateByPrimaryKeySelective(SavingsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_region
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    int updateByPrimaryKey(SavingsRegion record);
}