package com.fmall.springmvc.generate.mapper;

import com.fmall.springmvc.generate.pojo.SavingsProduct;
import com.fmall.springmvc.generate.pojo.SavingsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SavingsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int countByExample(SavingsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int deleteByExample(SavingsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int deleteByPrimaryKey(Integer savingsProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int insert(SavingsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int insertSelective(SavingsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    List<SavingsProduct> selectByExample(SavingsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    SavingsProduct selectByPrimaryKey(Integer savingsProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int updateByExampleSelective(@Param("record") SavingsProduct record, @Param("example") SavingsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int updateByExample(@Param("record") SavingsProduct record, @Param("example") SavingsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int updateByPrimaryKeySelective(SavingsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_detail
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    int updateByPrimaryKey(SavingsProduct record);
}