package com.fmall.springmvc.generate.mapper;

import com.fmall.springmvc.generate.pojo.SavingsType;
import com.fmall.springmvc.generate.pojo.SavingsTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SavingsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int countByExample(SavingsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int deleteByExample(SavingsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int deleteByPrimaryKey(Integer savingsTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int insert(SavingsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int insertSelective(SavingsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    List<SavingsType> selectByExample(SavingsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    SavingsType selectByPrimaryKey(Integer savingsTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int updateByExampleSelective(@Param("record") SavingsType record, @Param("example") SavingsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int updateByExample(@Param("record") SavingsType record, @Param("example") SavingsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int updateByPrimaryKeySelective(SavingsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savings_type
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    int updateByPrimaryKey(SavingsType record);
}