package com.fmall.springmvc.generate.pojo;

public class MyUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbggenerated Tue Sep 17 09:48:21 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }
}