package com.fmall.springmvc.generate.pojo;

import java.util.Date;

public class SavingsProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.savings_product_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private Integer savingsProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.bank_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.savings_type_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private Integer savingsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.region_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.product_interest_rate
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private String productInterestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.created_date
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.modified_date
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.created_by
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.modified_by
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.product_comments
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private String productComments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.product_name
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_detail.start_amt
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    private String startAmt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.savings_product_id
     *
     * @return the value of savings_detail.savings_product_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public Integer getSavingsProductId() {
        return savingsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.savings_product_id
     *
     * @param savingsProductId the value for savings_detail.savings_product_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setSavingsProductId(Integer savingsProductId) {
        this.savingsProductId = savingsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.bank_id
     *
     * @return the value of savings_detail.bank_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.bank_id
     *
     * @param bankId the value for savings_detail.bank_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.savings_type_id
     *
     * @return the value of savings_detail.savings_type_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public Integer getSavingsTypeId() {
        return savingsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.savings_type_id
     *
     * @param savingsTypeId the value for savings_detail.savings_type_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setSavingsTypeId(Integer savingsTypeId) {
        this.savingsTypeId = savingsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.region_id
     *
     * @return the value of savings_detail.region_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.region_id
     *
     * @param regionId the value for savings_detail.region_id
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.product_interest_rate
     *
     * @return the value of savings_detail.product_interest_rate
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public String getProductInterestRate() {
        return productInterestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.product_interest_rate
     *
     * @param productInterestRate the value for savings_detail.product_interest_rate
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setProductInterestRate(String productInterestRate) {
        this.productInterestRate = productInterestRate == null ? null : productInterestRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.created_date
     *
     * @return the value of savings_detail.created_date
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.created_date
     *
     * @param createdDate the value for savings_detail.created_date
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.modified_date
     *
     * @return the value of savings_detail.modified_date
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.modified_date
     *
     * @param modifiedDate the value for savings_detail.modified_date
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.created_by
     *
     * @return the value of savings_detail.created_by
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.created_by
     *
     * @param createdBy the value for savings_detail.created_by
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.modified_by
     *
     * @return the value of savings_detail.modified_by
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.modified_by
     *
     * @param modifiedBy the value for savings_detail.modified_by
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.product_comments
     *
     * @return the value of savings_detail.product_comments
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public String getProductComments() {
        return productComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.product_comments
     *
     * @param productComments the value for savings_detail.product_comments
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setProductComments(String productComments) {
        this.productComments = productComments == null ? null : productComments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.product_name
     *
     * @return the value of savings_detail.product_name
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.product_name
     *
     * @param productName the value for savings_detail.product_name
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_detail.start_amt
     *
     * @return the value of savings_detail.start_amt
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public String getStartAmt() {
        return startAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_detail.start_amt
     *
     * @param startAmt the value for savings_detail.start_amt
     *
     * @mbggenerated Sat Sep 21 23:03:34 CST 2013
     */
    public void setStartAmt(String startAmt) {
        this.startAmt = startAmt == null ? null : startAmt.trim();
    }
}