package com.fmall.springmvc.generate.pojo;

public class SavingsType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_type.savings_type_id
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    private Integer savingsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_type.currency_name
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    private String currencyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_type.savings_type_name
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    private String savingsTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_type.savings_term
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    private String savingsTerm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_type.savings_type_id
     *
     * @return the value of savings_type.savings_type_id
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    public Integer getSavingsTypeId() {
        return savingsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_type.savings_type_id
     *
     * @param savingsTypeId the value for savings_type.savings_type_id
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    public void setSavingsTypeId(Integer savingsTypeId) {
        this.savingsTypeId = savingsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_type.currency_name
     *
     * @return the value of savings_type.currency_name
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    public String getCurrencyName() {
        return currencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_type.currency_name
     *
     * @param currencyName the value for savings_type.currency_name
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName == null ? null : currencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_type.savings_type_name
     *
     * @return the value of savings_type.savings_type_name
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    public String getSavingsTypeName() {
        return savingsTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_type.savings_type_name
     *
     * @param savingsTypeName the value for savings_type.savings_type_name
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    public void setSavingsTypeName(String savingsTypeName) {
        this.savingsTypeName = savingsTypeName == null ? null : savingsTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_type.savings_term
     *
     * @return the value of savings_type.savings_term
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    public String getSavingsTerm() {
        return savingsTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_type.savings_term
     *
     * @param savingsTerm the value for savings_type.savings_term
     *
     * @mbggenerated Sat Sep 21 23:41:00 CST 2013
     */
    public void setSavingsTerm(String savingsTerm) {
        this.savingsTerm = savingsTerm == null ? null : savingsTerm.trim();
    }
}