package com.fmall.springmvc.generate.pojo;

public class SavingsRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_region.region_id
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_region.province
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_region.city
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_region.region_id
     *
     * @return the value of savings_region.region_id
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_region.region_id
     *
     * @param regionId the value for savings_region.region_id
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_region.province
     *
     * @return the value of savings_region.province
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_region.province
     *
     * @param province the value for savings_region.province
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_region.city
     *
     * @return the value of savings_region.city
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_region.city
     *
     * @param city the value for savings_region.city
     *
     * @mbggenerated Sat Sep 21 23:40:31 CST 2013
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}