package com.fmall.springmvc.generate.pojo;

public class SavingsBank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_bank.bank_id
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savings_bank.bank_name
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    private String bankName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_bank.bank_id
     *
     * @return the value of savings_bank.bank_id
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_bank.bank_id
     *
     * @param bankId the value for savings_bank.bank_id
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savings_bank.bank_name
     *
     * @return the value of savings_bank.bank_name
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savings_bank.bank_name
     *
     * @param bankName the value for savings_bank.bank_name
     *
     * @mbggenerated Sat Sep 21 23:39:42 CST 2013
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }
}